#!/usr/bin/env python3
"""Deterministic code generators for canonical schemas.

Currently registered generators:

- ``ts``      TypeScript types from all document schemas into
              ``packages/typescript/document-model/src/generated/``.
- ``pydantic`` Pydantic models from all document schemas into
              ``packages/python/document-model/src/document_model/generated/``.

Generated output must never be edited by hand; freshness is enforced by
``just generate-check``. ``just generate`` Ruff-formats the Pydantic module
after writing it so the committed file matches ``just fmt``.
"""

from __future__ import annotations

import json
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, cast

sys.path.insert(0, str(Path(__file__).resolve().parent))
from repo import ROOT

SCHEMA_ROOT = ROOT / "schemas"
DOCUMENT_SCHEMAS = (
    "common",
    "physical-document",
    "evidence",
    "layout-document",
    "semantic-document",
    "mapping",
)

TS_OUT = ROOT / "packages/typescript/document-model/src/generated"
PY_OUT = ROOT / "packages/python/document-model/src/document_model/generated"

TS_HEADER = "// Generated by scripts/generate.py from schemas/. DO NOT EDIT.\n"

PY_HEADER = "# Generated by scripts/generate.py from schemas/. DO NOT EDIT.\n"

PY_PREAMBLE = """from __future__ import annotations

from typing import Annotated, Any, ClassVar, Literal, cast

from pydantic import BaseModel, BeforeValidator, ConfigDict, Field, model_validator
from pydantic_core import PydanticCustomError

# All $defs names are globally unique across the canonical schemas, so
# this module is a flat namespace. Extra keys are forbidden everywhere
# except SemanticNode.attributes, which mirrors the open attribute bag.


def _json_integer(value: object) -> int:
    # JSON Schema accepts integral JSON numbers such as 2.0 as integers,
    # while rejecting booleans and strings that Pydantic would coerce.
    if isinstance(value, bool):
        raise PydanticCustomError("json_integer", "expected a JSON integer")
    if isinstance(value, int):
        return value
    if isinstance(value, float) and value.is_integer():
        return int(value)
    raise PydanticCustomError("json_integer", "expected a JSON integer")


def _reject_boolean_number(value: object) -> object:
    # Python equality conflates False/0 and True/1; JSON Schema does not.
    if isinstance(value, bool):
        raise PydanticCustomError("json_number", "expected a JSON number, not a boolean")
    return value


JsonInteger = Annotated[int, BeforeValidator(_json_integer)]


class _CanonicalModel(BaseModel):
    model_config = ConfigDict(strict=True, allow_inf_nan=False)
    __non_nullable_optional_fields__: ClassVar[frozenset[str]] = frozenset()
    __required_any_of__: ClassVar[tuple[frozenset[str], ...]] = ()

    @model_validator(mode="before")
    @classmethod
    def _validate_json_object(cls, value: object) -> object:
        if not isinstance(value, dict):
            return value
        data = cast("dict[str, object]", value)
        null_fields = cls.__non_nullable_optional_fields__.intersection(
            key for key, item in data.items() if item is None
        )
        if null_fields:
            names = ", ".join(sorted(null_fields))
            raise ValueError(f"explicit null is not allowed for: {names}")
        if cls.__required_any_of__ and not any(
            all(name in data for name in group) for group in cls.__required_any_of__
        ):
            choices = ", ".join("+".join(sorted(group)) for group in cls.__required_any_of__)
            raise ValueError(
                f"at least one required-property group must be present: {choices}"
            )
        return data
"""


@dataclass
class SchemaSet:
    """Loaded schemas plus a ref resolver across the set."""

    schemas: dict[str, dict[str, Any]]

    def resolve_ref(self, ref: str) -> tuple[str, str]:
        """Return (schema_name, def_name) for a canonical or relative ref."""
        base, _, pointer = ref.partition("#")
        tail = (
            base.split("/schemas/", 1)[-1]
            if "/schemas/" in base
            else base.replace("../", "").strip("/")
        )
        name = tail.split("/", 1)[0]
        pointer = pointer.removeprefix("/$defs/")
        return name, pointer


def load_schemas() -> SchemaSet:
    schemas: dict[str, dict[str, Any]] = {}
    for name in DOCUMENT_SCHEMAS:
        path = SCHEMA_ROOT / name / "schema.json"
        schemas[name] = json.loads(path.read_text(encoding="utf-8"))
    return SchemaSet(schemas=schemas)


def pascal(name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in name.replace("-", "_").split("_"))


def snake(name: str) -> str:
    return name.replace("-", "_")


def _resolve_def_ref(schema_set: SchemaSet, schema_name: str, ref: str) -> tuple[str, str]:
    """Resolve a $ref that may be intra-document ("#/$defs/X") or cross-document."""
    if ref.startswith("#/"):
        pointer = ref.removeprefix("#/$defs/")
        if pointer == ref:
            raise ValueError(f"unsupported intra-document ref pointer: {ref!r}")
        return schema_name, pointer
    return schema_set.resolve_ref(ref)


def _union_variants(
    schema_set: SchemaSet, schema_name: str, schema: dict[str, Any]
) -> list[tuple[str, str]]:
    """Variant (schema_name, def_name) pairs of a oneOf union of $refs."""
    variants: list[tuple[str, str]] = []
    for ref in schema.get("oneOf", []):
        if not isinstance(ref, dict) or "$ref" not in ref:
            raise ValueError(f"union with unsupported variant: {ref!r} in {schema_name}")
        variants.append(_resolve_def_ref(schema_set, schema_name, ref["$ref"]))
    return variants


def _dedupe(values: list[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for value in values:
        if value not in seen:
            seen.add(value)
            out.append(value)
    return out


# ---------------------------------------------------------------------------
# shared type analysis
# ---------------------------------------------------------------------------


@dataclass
class FieldInfo:
    name: str
    schema: dict[str, Any]
    required: bool


def _is_nullable(schema: dict[str, Any]) -> bool:
    """True when JSON Schema allows JSON null (not merely omitting the key)."""
    types = schema.get("type")
    if types == "null" or (isinstance(types, list) and "null" in types):
        return True
    for key in ("anyOf", "oneOf"):
        for sub in schema.get(key, []):
            if isinstance(sub, dict) and sub.get("type") == "null":
                return True
    return False


def _annotation_includes_none(annotation: str) -> bool:
    return annotation == "None" or annotation.endswith("| None") or "| None |" in annotation


def _object_fields(schema: dict[str, Any]) -> list[FieldInfo] | None:
    if schema.get("type") != "object" or "properties" not in schema:
        return None
    required = set(schema.get("required", []))
    fields = []
    for name, subschema in schema["properties"].items():
        fields.append(FieldInfo(name=name, schema=subschema, required=name in required))
    return fields


def _required_any_of_groups(schema: dict[str, Any]) -> tuple[tuple[str, ...], ...]:
    """Return supported object-level ``anyOf`` required-property groups."""
    groups: list[tuple[str, ...]] = []
    for variant in schema.get("anyOf", []):
        if set(variant) != {"required"} or not isinstance(variant["required"], list):
            raise ValueError(f"unsupported object anyOf variant: {variant!r}")
        required = tuple(variant["required"])
        if not required or not all(isinstance(name, str) for name in required):
            raise ValueError(f"invalid object anyOf required group: {variant!r}")
        groups.append(required)
    return tuple(groups)


def _def_sort_key(item: tuple[str, dict[str, Any]]) -> tuple[int, str]:
    """Emit enums first so objects can reference them; otherwise alphabetical."""
    name, schema = item
    kind = 0 if schema.get("enum") or "const" in schema else 1
    return (kind, name)


# ---------------------------------------------------------------------------
# TypeScript generator
# ---------------------------------------------------------------------------


class TsGenerator:
    """Generates TS type declarations from the canonical schemas."""

    def __init__(self, schema_set: SchemaSet) -> None:
        self.set = schema_set
        self.lines: list[str] = []
        self.generated: set[tuple[str, str]] = set()

    # -- type expression ----------------------------------------------------

    def type_of(self, schema_name: str, schema: dict[str, Any], indent: str) -> str:  # noqa: PLR0911
        if "$ref" in schema:
            target_name, def_name = _resolve_def_ref(self.set, schema_name, schema["$ref"])
            return f"{pascal(target_name)}.{pascal(def_name)}"
        if "oneOf" in schema:
            rendered = [
                self.type_of(target_name, {"$ref": f"#/$defs/{def_name}"}, indent)
                for target_name, def_name in _union_variants(self.set, schema_name, schema)
            ]
            return " | ".join(_dedupe(rendered))
        if "anyOf" in schema:
            rendered = []
            for sub in schema["anyOf"]:
                if "$ref" in sub:
                    target_name, def_name = _resolve_def_ref(self.set, schema_name, sub["$ref"])
                    rendered.append(f"{pascal(target_name)}.{pascal(def_name)}")
                elif "enum" in sub or "const" in sub or "type" in sub:
                    rendered.append(self.type_of(schema_name, sub, indent))
                else:
                    raise ValueError(f"unsupported anyOf variant: {json.dumps(sub)[:200]}")
            return " | ".join(_dedupe(rendered))
        if "const" in schema:
            return json.dumps(schema["const"], ensure_ascii=False)
        if "enum" in schema:
            return " | ".join(json.dumps(v, ensure_ascii=False) for v in schema["enum"])
        types = schema.get("type")
        if isinstance(types, list):
            return " | ".join(self._primitive(t) for t in types)
        if isinstance(types, str):
            if types == "array":
                items = schema.get("items")
                if isinstance(items, dict):
                    return f"{self.type_of(schema_name, items, indent)}[]"
                return "unknown[]"
            if types == "object" and "properties" not in schema:
                return "Record<string, unknown>"
            return self._primitive(types)
        raise ValueError(f"cannot render type for schema: {json.dumps(schema)[:200]}")

    @staticmethod
    def _primitive(type_name: str) -> str:
        return {
            "string": "string",
            "number": "number",
            "integer": "number",
            "boolean": "boolean",
            "array": "unknown[]",
            "object": "Record<string, unknown>",
            "null": "null",
        }.get(type_name, "unknown")

    # -- emission -----------------------------------------------------------

    def emit(self) -> str:
        out: list[str] = [TS_HEADER, "// prettier-ignore", ""]
        for schema_name in DOCUMENT_SCHEMAS:
            schema = self.set.schemas[schema_name]
            defs = schema.get("$defs", {})
            out.append(f"export declare namespace {pascal(schema_name)} {{")
            for def_name, def_schema in sorted(defs.items(), key=_def_sort_key):
                out.append(self._emit_def(schema_name, def_name, def_schema, "  "))
            out.append("}")
            out.append("")
        return "\n".join(out).rstrip() + "\n"

    def _emit_def(
        self, schema_name: str, def_name: str, schema: dict[str, Any], indent: str
    ) -> str:
        key = (schema_name, def_name)
        del key  # names are fully qualified by namespace; no memoization needed
        ts_name = pascal(def_name)
        doc = schema.get("description")
        lines: list[str] = []
        if doc:
            lines.append(f"{indent}/** {doc} */")
        if "const" in schema:
            lines.append(f"{indent}export type {ts_name} = {json.dumps(schema['const'])};")
            return "\n".join(lines)
        if "enum" in schema:
            values = " | ".join(json.dumps(v, ensure_ascii=False) for v in schema["enum"])
            lines.append(f"{indent}export type {ts_name} = {values};")
            return "\n".join(lines)
        if "oneOf" in schema:
            rendered = [
                f"{pascal(target_name)}.{pascal(def_name)}"
                for target_name, def_name in _union_variants(self.set, schema_name, schema)
            ]
            lines.append(f"{indent}export type {ts_name} = " + " | ".join(_dedupe(rendered)) + ";")
            return "\n".join(lines)
        fields = _object_fields(schema)
        if fields is not None:
            required_any_of = _required_any_of_groups(schema)
            declaration = "type" if required_any_of else "interface"
            operator = " =" if required_any_of else ""
            lines.append(f"{indent}export {declaration} {ts_name}{operator} {{")
            for field in fields:
                field_doc = field.schema.get("description")
                if field_doc:
                    lines.append(f"{indent}  /** {field_doc} */")
                optional = "" if field.required else "?"
                field_type = self.type_of(schema_name, field.schema, indent)
                lines.append(f"{indent}  {field.name}{optional}: {field_type};")
            lines.append(f"{indent}}}")
            if required_any_of:
                lines[-1] += " & ("
                fields_by_name = {field.name: field for field in fields}
                for group in required_any_of:
                    required_fields = "; ".join(
                        f"{name}: {self.type_of(schema_name, fields_by_name[name].schema, indent)}"
                        for name in group
                    )
                    lines.append(f"{indent}  | {{ {required_fields} }}")
                lines.append(f"{indent});")
            return "\n".join(lines)
        # type alias for constrained primitives (pattern ids, bounded numbers, ...)
        return "\n".join(
            [
                *lines,
                f"{indent}export type {ts_name} = {self.type_of(schema_name, schema, indent)};",
            ]
        )


def generate_ts(schema_set: SchemaSet) -> str:
    return TsGenerator(schema_set).emit()


# ---------------------------------------------------------------------------
# Pydantic generator
# ---------------------------------------------------------------------------


class PydanticGenerator:
    """Generates a flat Pydantic module from the canonical schemas.

    All ``$defs`` names are globally unique across the six schemas, so defs
    are emitted at module level. oneOf unions become plain union aliases;
    tagged variants keep their Literal discriminator fields.
    """

    def __init__(self, schema_set: SchemaSet) -> None:
        self.set = schema_set

    # -- annotations ----------------------------------------------------------

    def annotation(self, schema_name: str, schema: dict[str, Any]) -> str:  # noqa: PLR0911
        if "$ref" in schema:
            _, def_name = _resolve_def_ref(self.set, schema_name, schema["$ref"])
            return pascal(def_name)
        if "oneOf" in schema:
            rendered = [
                self.annotation(target_name, {"$ref": f"#/$defs/{def_name}"})
                for target_name, def_name in _union_variants(self.set, schema_name, schema)
            ]
            return " | ".join(_dedupe(rendered))
        if "anyOf" in schema:
            rendered = []
            for sub in schema["anyOf"]:
                if "$ref" in sub:
                    _, def_name = _resolve_def_ref(self.set, schema_name, sub["$ref"])
                    rendered.append(pascal(def_name))
                elif "enum" in sub or "const" in sub or "type" in sub:
                    rendered.append(self.annotation(schema_name, sub))
                else:
                    raise ValueError(f"unsupported anyOf variant: {json.dumps(sub)[:200]}")
            return " | ".join(_dedupe(rendered))
        if "enum" in schema:
            values = ", ".join(json.dumps(v, ensure_ascii=False) for v in schema["enum"])
            return f"Literal[{values}]"
        if "const" in schema:
            value = schema["const"]
            return f"Literal[{json.dumps(value, ensure_ascii=False)}]"
        types = schema.get("type")
        if isinstance(types, list):
            return " | ".join(self._primitive(t) for t in types)
        if isinstance(types, str):
            if types == "array":
                items = schema.get("items")
                if isinstance(items, dict):
                    return f"list[{self.annotation(schema_name, items)}]"
                return "list[Any]"
            if types == "object" and "properties" not in schema:
                return "dict[str, Any]"
            return self._primitive(types)
        raise ValueError(f"cannot render annotation for: {json.dumps(schema)[:200]}")

    @staticmethod
    def _primitive(type_name: str) -> str:
        return {
            "string": "str",
            "number": "float",
            "integer": "JsonInteger",
            "boolean": "bool",
            "array": "list[Any]",
            "object": "dict[str, Any]",
            "null": "None",
        }.get(type_name, "Any")

    # -- emission ---------------------------------------------------------------

    def emit(self) -> str:
        out = cast("list[str]", (PY_HEADER + "\n" + PY_PREAMBLE).splitlines())
        for schema_name in DOCUMENT_SCHEMAS:
            schema = self.set.schemas[schema_name]
            defs = schema.get("$defs", {})
            out.append(f"# --- {schema_name} " + "-" * max(1, 56 - len(schema_name)))
            out.append("")
            # First pass: object classes (they may be referenced by aliases).
            # Document schemas also expose their root object as a model.
            roots: list[tuple[str, dict[str, Any]]] = []
            if schema.get("type") == "object" and "properties" in schema:
                roots.append((schema["title"], schema))
            for def_name, def_schema in sorted(defs.items(), key=_def_sort_key):
                if _object_fields(def_schema) is not None:
                    out.extend(self._emit_def(schema_name, def_name, def_schema))
            for root_name, root_schema in roots:
                out.extend(self._emit_def(schema_name, root_name, root_schema))
            # Second pass: aliases (enums, ids, unions, constrained primitives).
            for def_name, def_schema in sorted(defs.items(), key=_def_sort_key):
                if _object_fields(def_schema) is None:
                    out.extend(self._emit_def(schema_name, def_name, def_schema))
        return "\n".join(out).rstrip() + "\n"

    def _emit_def(  # noqa: PLR0911
        self, schema_name: str, def_name: str, schema: dict[str, Any]
    ) -> list[str]:
        name = pascal(def_name)
        doc = schema.get("description")
        doc_line = f"# {doc}" if doc else None
        if "const" in schema:
            literal = json.dumps(schema["const"], ensure_ascii=False)
            return self._alias(name, literal, doc_line)
        if "enum" in schema:
            values = ", ".join(json.dumps(v, ensure_ascii=False) for v in schema["enum"])
            literal = f"Literal[{values}]"
            has_numeric = any(
                isinstance(value, (int, float)) and not isinstance(value, bool)
                for value in schema["enum"]
            )
            has_boolean = any(isinstance(value, bool) for value in schema["enum"])
            if has_numeric and has_boolean:
                raise ValueError(f"mixed Boolean/numeric enum is unsupported: {name}")
            if has_numeric:
                literal = f"Annotated[{literal}, BeforeValidator(_reject_boolean_number)]"
            return self._alias(name, literal, doc_line)
        if "oneOf" in schema:
            rendered = [
                pascal(variant_def)
                for _, variant_def in _union_variants(self.set, schema_name, schema)
            ]
            return self._alias(name, " | ".join(_dedupe(rendered)), doc_line)
        fields = _object_fields(schema)
        if fields is None:
            ann = self.annotation(schema_name, schema)
            constraints = self._constraint_parts(schema)
            if constraints:
                return self._alias(
                    name, f"Annotated[{ann}, Field({', '.join(constraints)})]", doc_line
                )
            return self._alias(name, ann, doc_line)

        lines: list[str] = [f"class {name}(_CanonicalModel):"]
        if doc_line:
            lines.append(f"    {doc_line}")
        allow_extra = schema_name == "semantic-document" and def_name == "SemanticNode"
        extra = 'extra="allow"' if allow_extra else 'extra="forbid"'
        lines.append(f"    model_config = ConfigDict({extra}, strict=True, allow_inf_nan=False)")
        non_nullable_optional = frozenset(
            field.name for field in fields if not field.required and not _is_nullable(field.schema)
        )
        if non_nullable_optional:
            rendered = ", ".join(repr(item) for item in sorted(non_nullable_optional))
            lines.append(
                "    __non_nullable_optional_fields__: ClassVar[frozenset[str]] = "
                f"frozenset({{{rendered}}})"
            )
        required_any_of = _required_any_of_groups(schema)
        if required_any_of:
            rendered_groups = ", ".join(
                f"frozenset({{{', '.join(repr(item) for item in group)}}})"
                for group in required_any_of
            )
            if len(required_any_of) == 1:
                rendered_groups += ","
            lines.append(
                "    __required_any_of__: ClassVar[tuple[frozenset[str], ...]] = "
                f"({rendered_groups})"
            )
        if not fields:
            lines.append("    pass")
            lines.append("")
            return lines
        for field in fields:
            lines.append(self._field_line(schema_name, field))
        lines.append("")
        return lines

    def _field_line(self, schema_name: str, field: FieldInfo) -> str:
        """Render one model field.

        JSON Schema optional means the key may be omitted, not that JSON null
        is allowed. Null is only accepted when the schema itself is nullable
        (``type: null`` or ``anyOf``/``oneOf`` including null).
        """
        fname = field.name
        ann = self.annotation(schema_name, field.schema)
        constraints = self._constraint_parts(field.schema)
        if not field.required and not _annotation_includes_none(ann):
            ann = f"{ann} | None"
        args: list[str] = []
        if not field.required:
            args.append("default=None")
        args.extend(constraints)
        if args:
            return f"    {fname}: {ann} = Field({', '.join(args)})"
        return f"    {fname}: {ann}"

    @staticmethod
    def _alias(name: str, value: str, doc_line: str | None) -> list[str]:
        lines = []
        if doc_line:
            lines.append(doc_line)
        lines.append(f"{name} = {value}")
        lines.append("")
        return lines

    @staticmethod
    def _constraint_parts(schema: dict[str, Any]) -> list[str]:
        parts: list[str] = []
        if schema.get("minimum") is not None:
            parts.append(f"ge={schema['minimum']}")
        if schema.get("maximum") is not None:
            parts.append(f"le={schema['maximum']}")
        if schema.get("exclusiveMinimum") is not None:
            parts.append(f"gt={schema['exclusiveMinimum']}")
        if schema.get("exclusiveMaximum") is not None:
            parts.append(f"lt={schema['exclusiveMaximum']}")
        if schema.get("minItems") is not None:
            parts.append(f"min_length={schema['minItems']}")
        if schema.get("maxItems") is not None:
            parts.append(f"max_length={schema['maxItems']}")
        if schema.get("minLength") is not None:
            parts.append(f"min_length={schema['minLength']}")
        if schema.get("maxLength") is not None:
            parts.append(f"max_length={schema['maxLength']}")
        if schema.get("multipleOf") is not None:
            parts.append(f"multiple_of={schema['multipleOf']}")
        if schema.get("pattern") is not None:
            parts.append(f"pattern={json.dumps(schema['pattern'])}")
        return parts


def generate_pydantic(schema_set: SchemaSet) -> str:
    return PydanticGenerator(schema_set).emit()


# ---------------------------------------------------------------------------
# entry point
# ---------------------------------------------------------------------------

GENERATORS: dict[str, Any] = {
    "ts": ("packages/typescript/document-model/src/generated/schema.ts", generate_ts),
    "pydantic": (
        "packages/python/document-model/src/document_model/generated/schema_models.py",
        generate_pydantic,
    ),
}


def _format_python(content: str, source_path: Path) -> str:
    """Ruff-format generated Python so freshness checks match ``just fmt``.

    ``--stdin-filename`` keeps Ruff's config discovery on the real output
    path (line length, excludes) instead of a temporary file under ``/tmp``.
    """
    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "ruff",
            "format",
            "--stdin-filename",
            str(source_path),
            "-",
        ],
        check=True,
        capture_output=True,
        text=True,
        input=content,
        cwd=ROOT,
    )
    formatted: str = result.stdout
    return formatted


def main() -> int:
    schema_set = load_schemas()
    only = sys.argv[1] if len(sys.argv) > 1 else None
    names = [only] if only in GENERATORS else list(GENERATORS)
    for name in names:
        rel_path, func = GENERATORS[name]
        out_path = ROOT / rel_path
        out_path.parent.mkdir(parents=True, exist_ok=True)
        content = func(schema_set)
        if name == "pydantic":
            content = _format_python(content, out_path)
        previous = out_path.read_text(encoding="utf-8") if out_path.is_file() else None
        if previous != content:
            out_path.write_text(content, encoding="utf-8")
            print(f"generated {rel_path}")
        else:
            print(f"up-to-date {rel_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
